#!/bin/bash
#Author: Vishnu Pradeep
#Email: intermedia.vishnu@gmail.com



if [ -n "$1" ]; then
	service apache2 stop 
	service nginx stop  	
	if [ "$1" == a ]; then
		service apache2 start 
	elif [ "$1" == n ]; then
		service nginx start 
	else
		service apache2 start 
	fi
else
	echo "No server specified. a for apache and n for nginx"
fi
	
