#!/bin/bash
#More scripts at https://github.com/intermediatech/help-me-do-it
# Released Under GPL v2 Licence

#CSS
mkdir css
cd css
touch main.css
echo "body{
  background-color:red;
  }">main.css
cd ..

#IMG
mkdir img

#JS
mkdir js
cd js
touch main.js
cd ..

#Main
touch index.php
echo "<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
<?php echo 'Skelton created. :-)'?>
</body>
</html>
" > index.php
