#!/bin/bash
# Author: Vishnu Pradeep
# Email: intermedia.vishnu@gmail.com
# More scripts at https://github.com/intermediatech/help-me-do-it
# Released Under GPL v2 Licence

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
  then
    echo "./web_skelton css_folder_name js_folder_name"
    echo "Example: ./web_skelton css js"
fi

#CSS
mkdir css
cd css
touch main.css
echo "body{
  background-color:red;
  }">main.css
cd ..

#IMG
mkdir img

#JS
mkdir js
cd js
touch main.js
cd ..

#Main
touch index.php
echo "<html>
<head>
	<link rel="stylesheet" type="text/css" href="css/main.css">
</head>
<body>
<?php echo 'Skelton created. :-)'?>
</body>
</html>
" > index.php
