#!/bin/bash
playlist="http://www.youtube.com/playlist?list="
if [ -n "$1" ]; then
	youtube-dl --max-quality mp4 $1  -o "%(stitle)s.mp4"
else
	youtube-dl --max-quality mp4 $playlist  -o "%(stitle)s.mp4"
fi
